### ISSUE TITLE
DOPModule CMakeLists.txt references non-existent SeeBranch.exports symbol file

### ISSUE THREAD

**Issue by thomasnyman** [melynx/DOP-StaticAssist#1]
`Custom/DOPModule/CMakeLists.txt` references a non-existent `SeeBranch.exports` symbol file on line 5:

    set(LLVM_EXPORTED_SYMBOL_FILE ${CMAKE_CURRENT_SOURCE_DIR}/SeeBranch.exports)

This causes a build failure during the `Scanning dependencies of target LLVMSeeBranch_exports` step:

    make[2]: *** No rule to make target 'lib/DOPModule/SeeBranch.exports', needed by 'lib/DOPModule/LLVMSeeBranch.exports'.  Stop.

**Comment by huhong789** [comment]
Thanks for correcting the error! I have merged the code.
