### ISSUE TITLE
How can I compile those applications into LLVM IR?

### ISSUE THREAD

**Issue by skyel1u** [melynx/DOP-StaticAssist#3]
In the paper: *Data-Oriented Programming: On the Expressiveness of Non-control Data Attacks*, the table VI(*Section IV, D. Attack Construction*) shows those applications contain some DOP Gadgets which can use the LLVMDOPModule locate. However, the LLVMDOPModule can only reads LLVM IR files. And now, how can I compile the applications such as ProFTPD into LLVM IR?

![image](https://user-images.githubusercontent.com/16306294/55669219-51670700-58a7-11e9-8e56-371713f2e24a.png)

**Comment by huhong789** [comment]
Try wllvm https://github.com/travitch/whole-program-llvm

**Comment by skyel1u** [comment]
Thanks a lot, I'll try.
